[0m10:46:02.096140 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FC56BF0E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FC4568B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FC636EE90>]}


============================== 10:46:02.238986 | 6bd27045-2157-49ba-a4e7-4afe794cd0aa ==============================
[0m10:46:02.238986 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:46:02.239923 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\elvir\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init dbt_groupp', 'send_anonymous_usage_stats': 'True'}
[0m10:46:02.748440 [debug] [MainThread]: Starter project path: C:\Users\elvir\source\repos\AI2_group_project\.venv\Lib\site-packages\dbt\include\starter_project
[0m10:46:02.781704 [info ] [MainThread]: 
Your new dbt project "dbt_groupp" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:46:02.782707 [info ] [MainThread]: Setting up your profile.
[0m10:46:04.971092 [debug] [MainThread]: Command `dbt init` succeeded at 10:46:04.970807 after 3.08 seconds
[0m10:46:04.971858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FC79AE780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FC7C344D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FC78F3F00>]}
[0m10:46:04.972563 [debug] [MainThread]: Flushing usage events
[0m10:46:05.404865 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:07:08.209677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002437A874AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024378554050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024378391A90>]}


============================== 11:07:08.219175 | 518cd720-cd3e-4f3c-9a01-d5a3dcbda719 ==============================
[0m11:07:08.219175 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:07:08.220738 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\elvir\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt deps', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:07:08.221814 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\elvir\source\repos\AI2_group_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:07:08.223952 [debug] [MainThread]: Command `dbt deps` failed at 11:07:08.223716 after 0.20 seconds
[0m11:07:08.224660 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002437B637CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002437B5DB1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002437B7B46B0>]}
[0m11:07:08.225367 [debug] [MainThread]: Flushing usage events
[0m11:07:08.642495 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:13:09.206749 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FFA290980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FFAD20050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FF7DBD810>]}


============================== 11:13:09.216753 | a9b0f010-b338-4c98-8162-483c029f0354 ==============================
[0m11:13:09.216753 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:13:09.218466 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\elvir\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:13:09.219664 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\elvir\source\repos\AI2_group_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:13:09.221775 [debug] [MainThread]: Command `dbt deps` failed at 11:13:09.221459 after 0.20 seconds
[0m11:13:09.222495 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FFB0968B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FFAFF2F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FFB1F8160>]}
[0m11:13:09.223155 [debug] [MainThread]: Flushing usage events
[0m11:13:09.651630 [debug] [MainThread]: An error was encountered while trying to flush usage events
